http:
  host: "0.0.0.0"
  port: "8081"
  path: "/action"
  
anypoint:
  username: "SelfLearn"
  password: "LearnMule#2023"
  
 
  bg: "Student"
  enviroment: "Sandbox"
  region: "us-east-2"
  workers: "1"
  workerType: "Micro"
  property: "env"

app:
  name: "gitaction"
  runtime: "4.4.0"